feat: add sum function
js-tasks-ru/js-20220209_i-kukarkin pull request #1
Opened 2022-02-10 18:03 UTC by IlyaKukarkin

2022-02-12 11:49 UTC, dosandk approved these changes
good first step 👍

2022-02-12 15:45 UTC, dosandk submitted a review, later dismissed
👍

2022-02-15 22:12 UTC, dosandk commented on 01-intro/1-sum/index.js
> +  return m + n;
good 👍

2022-02-15 22:13 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  const copyArr = arr.slice();
более современный способ копирования массива:
```
const copy = [...arr]
```

2022-02-15 22:13 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
Подумайте как исправить решение таким образом чтобы избавиться от `reverse` и сортировать данные сразу в верном порядке

2022-02-15 22:13 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +const compareWords = (a, b) => {
good 👍

2022-02-15 22:13 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +  return Object.entries(obj).filter(([key]) => fields.includes(key)).reduce((prev, [key, value]) => ({...prev, [key]: value}), {});
good 👍

2022-02-15 22:13 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +  return Object.entries(obj).filter(([key]) => !fields.includes(key)).reduce((prev, [key, value]) => ({...prev, [key]: value}), {});
good 👍

2022-02-15 22:13 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2022-02-16 16:23 UTC, IlyaKukarkin commented on 02-javascript-data-types/1-sort-strings/index.js
Поправил

2022-02-16 16:23 UTC, IlyaKukarkin commented on 02-javascript-data-types/1-sort-strings/index.js
> +  const copyArr = arr.slice();
Поправил

2022-02-17 19:16 UTC, IlyaKukarkin commented on 03-objects-arrays-intro-to-testing/3-trim-symbols/index.js
> +  string.split('').forEach((letter) => {
Не догадался тут до чего-то "Хитрого", только придумал пробежать циклом 🙃

2022-02-19 10:33 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
>  export function createGetter(path) {
good 👍

2022-02-19 10:33 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +  return (obj) => {
👍 good

2022-02-19 10:33 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +        return undefined;
помните на занятии мы говорили что `undefined` мы не присваиваем и не возвращаем?
поэтому тут нужно просто выполнить `return`

2022-02-19 10:33 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
> +    return undefined;
`return`

2022-02-19 10:34 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/3-trim-symbols/index.js
>  export function trimSymbols(string, size) {
good 👍

2022-02-19 10:34 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/4-uniq/index.js
> +  return [...new Set(arr).values()];
достаточно без `values`:
```
return [...new Set(arr)]
```

2022-02-19 10:34 UTC, dosandk approved these changes
good 👍

2022-02-19 10:46 UTC, dosandk approved these changes
good 👍

2022-02-19 10:55 UTC, merged